version: "3.1"

volumes:
    postgres-data: ~

services:
  app:
    container_name: scat-app
    build: .
    command: go-watch.sh
    volumes:
      - ./src:/go/src/app
      - $GOPATH/pkg/mod:/go/pkg/mod
    working_dir: /go/src/app
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT
      - GOPATH=/go
    links:
      - db
    restart:
      always
  db:
    image: postgres:10.4-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - ${DATABASE_HOST_PORT}:5432
    environment:
      POSTGRES_DB:       scat
      POSTGRES_USER:     dev
      POSTGRES_PASSWORD: dev

